### ISSUE TITLE
Fails to work on Windows machine

### ISSUE THREAD

**Issue by aleccool213** [lowlighter/setup-velociraptor#5]
This Github Action fails to work out of the box on Windows machines.

Github Actions YML:

```yml
jobs:
  test-and-build:
    runs-on: 
    strategy:
      matrix: x86_64-pc-windows-msvc
        deno-version: ["v1.15.3"]

  steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Use Deno v1.15.3
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.15.3

      - name: Setup Velociraptor
        uses: jurassiscripts/setup-velociraptor@v1

      - name: Check formatting
        run: vr run format
```

Output:
![Xnip2021-11-15_09-09-43](https://user-images.githubusercontent.com/6475934/141824599-5fdc8f53-9e8c-4ed2-9f67-09d50a932c42.jpg)
